---
name: cmpsc-300-spring-2021-lab2
break: true
indent: 4
---

# --> check the technical writing
writing/reflection.md:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the code1
src/baseCounter.py:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the code2
src/dnaComp.py:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the number of commits beyond a threshold
CountCommits --count 3
